# Generated by Django 3.1.6 on 2021-02-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CPF',
            field=models.CharField(help_text='Apenas números', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True, null=True, verbose_name='Usuário ativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='complement',
            field=models.CharField(help_text='Número do apartamento, ponto de referência, bloco, etc.', max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=45, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_number',
            field=models.IntegerField(null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='user',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=45, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_name',
            field=models.CharField(help_text='Este será o nome exibido no seu perfil.', max_length=60, null=True, verbose_name='Nome de exibição'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=255, null=True, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_organizer',
            field=models.BooleanField(default=False, null=True, verbose_name='É Organizador'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_participant',
            field=models.BooleanField(default=False, null=True, verbose_name='É Participante'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=60, verbose_name='Nome de usuário'),
        ),
    ]
