# Generated by Django 3.1.6 on 2021-02-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
