# Generated by Django 3.1.6 on 2021-02-17 01:01

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210216_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default=-1, max_length=45, verbose_name='Senha'),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default=-1, max_length=45, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=-1, help_text='Requerido. 15 caracteres ou menos. Letras, numeros e @/./+/-/_ characters', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Enter a valid username.', 'invalid')], verbose_name='Nome de usuário'),
        ),
    ]
