# Generated by Django 3.1.6 on 2021-02-17 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210216_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='district',
            new_name='city',
        ),
    ]
