# Generated by Django 3.1.6 on 2021-02-17 15:06

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210217_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='show_name',
            field=models.CharField(help_text='Requerido. 15 caracteres ou menos. Letras, numeros e @/./+/-/_ characters', max_length=60, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Enter a valid username.', 'invalid')], verbose_name='Nome de exibição'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=60, verbose_name='Nome de usuário'),
        ),
    ]
