# Generated by Django 3.1.6 on 2021-02-17 15:19

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210217_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='show_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Requerido. 15 caracteres ou menos. Letras, números e os seguintes caracteres: @/./+/-/_ ', max_length=60, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Insira um username valido.', 'invalido')], verbose_name='Username'),
        ),
    ]
