# Generated by Django 3.1.6 on 2021-02-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210211_1450'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_type',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.event', verbose_name='Evento'),
        ),
    ]
