# Generated by Django 3.1.6 on 2021-02-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210211_1450'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cost',
            field=models.FloatField(verbose_name='Valor (R$)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_datetime',
            field=models.DateTimeField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(help_text='Local onde o evento ocorrerá. Pode ser um endereço, uma sala, etc.', max_length=255, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subscription_limit',
            field=models.IntegerField(default=0, help_text='Para atividades sem limite de inscrições, use 0.', null=True, verbose_name='Limite de inscrições'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='event',
            name='activity_limit',
            field=models.IntegerField(help_text='Para eventos sem limite de atividades, use 0.', null=True, verbose_name='Limite de atividades para inscrição'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='organize_event',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='organize_event',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user', verbose_name='Usuário'),
        ),
    ]
